# Google Plugins
google_analytics:
  tracking_id: UA-129758206-1

# Facebook SDK Support
facebook_sdk:
  app_id: 2470546159839111
  fb_admin: 100001106016019

## hexo-all-minifier
html_minifier:
  enable: true

css_minifier:
  enable: true

js_minifier:
  enable: true

js_concator:
  # enable: true

image_minifier:
  enable: true