# Google Plugins
google_analytics:
  tracking_id: <GOOGLE_ANALYTICS_TRACKING_ID>

# Facebook SDK Support
facebook_sdk:
  app_id: <FB_SDK_APP_ID>
  fb_admin: <FB_SDK_ADMIN_ID>

## hexo-all-minifier
html_minifier:
  enable: true

css_minifier:
  enable: true

js_minifier:
  enable: true

js_concator:
  enable: true

image_minifier:
  enable: true